name: techlead
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.0.7
  cached_network_image: ^3.3.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  intl: ^0.19.0
  file_picker: ^9.1.0
  provider: ^6.1.2
  font_awesome_flutter: ^9.0.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: any
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.11.0
  slide_to_act: ^2.0.1
  month_year_picker: ^0.4.0+1
  geocoding: ^2.0.5
  permission_handler: ^11.2.0
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  mailer: ^6.1.2
  excel: ^2.0.8
  dio: ^5.1.2
  open_file: ^3.2.1
  carousel_slider: ^5.0.0
  google_maps_webservice:
  lottie: ^1.1.0
  docx_template: ^0.4.0
  pdf: ^3.6.3
  http: ^0.13.0
  flutter_dotenv: ^5.0.2
  share_plus: ^10.1.4
  google_fonts: ^4.0.4
  sqflite: ^2.3.2
  fl_chart: ^0.70.2
  pie_chart: ^5.4.0
  google_maps_flutter_android: ^2.14.14
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_new_badger: ^1.1.1
  flutter_pdfview: ^1.4.0
  url_launcher: ^6.2.5
  pdfx: ^2.8.0
  screenshot: ^3.0.0
  dropdown_search: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
